### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by haileylgbt** [asl97-websites/minecoredevteam#2]
Just make pull requests to me and I'll pr over to the original! ;)

**Comment by asl97** [comment]
The original is gone, if you read the description of this organization on ether the organization profile page or site, you know whatever changes I did usually shouldn't be merge back upstream if there is even an upstream.

https://asl97-websites.github.io/
```
This organization is about bring back websites which was brought down or otherwise unavailable but with the source still existing on github.

Attempt are make to keep all internal links working, external link aren't guarantee to work.

Functionality aren't guarantee but we will try our best to get everything working on the site.
```

https://asl97-websites.github.io/minecoredevteam/
